### ISSUE TITLE
Add a README.md

### ISSUE THREAD

**Issue by Soumya44** [Google-Front-End-Weekend-Projects/A-Tribute-To-Stephen-Hawking#1]
Please, someone, add a Readme file.

**Comment by bhaskarSingh** [comment]
What should the readme file be about? how to contribute or about the project itself.

**Comment by Logan1x** [comment]
First about the project and then how to contribute. if you want to do this I am happy to help/guide you on this

**Comment by bhaskarSingh** [comment]
any guidance would be helpful @Logan1x

**Comment by Logan1x** [comment]
We can use [this](https://github.com/Logan1x/Python-Scripts/blob/master/README.md#contributor-list) script to generate contributors list. It will look like [this](https://github.com/Logan1x/Python-Scripts#contributors),


![image](https://user-images.githubusercontent.com/10944610/37860951-e823c100-2f55-11e8-8cfa-efa0b5699b30.png)

**Comment by Logan1x** [comment]
about the project (content idea should be given by @Soumya44 or anyone who is working on this) or you can copy from the article/post prepared.

**Comment by Soumya44** [comment]
Hey, Logan1x you can generate a readme.md using your python script. That will be cool.
