### ISSUE TITLE
Add a Timeline Of Stephen Hawking 

### ISSUE THREAD

**Issue by Soumya44** [Google-Front-End-Weekend-Projects/A-Tribute-To-Stephen-Hawking#13]

**Comment by ibrahimkundlik** [comment]
Do we need to create an entire new page or just include the timeline in homepage?

**Comment by rahuldcoder** [comment]
I am creating a page for the timeline.

**Comment by rahuldcoder** [comment]
I have improved the visibility of timeline page.
![timeline](https://user-images.githubusercontent.com/18399319/37890734-4ad5248e-30ef-11e8-8588-e14d430597da.png)

**Comment by rahuldcoder** [comment]
Also, I have combined the stylesheet with the main stylesheet as everyone was asking to remove repeated code.
