### ISSUE TITLE
Add a Cool Footer

### ISSUE THREAD

**Issue by Soumya44** [Google-Front-End-Weekend-Projects/A-Tribute-To-Stephen-Hawking#2]
Add a Cool Footer that will contain some social media icons.

**Comment by rahuldcoder** [comment]
I have added footer containing social media icons.
![nanodegree](https://user-images.githubusercontent.com/18399319/37793383-87b30000-2e34-11e8-8b4a-999141cb76ba.png)

**Comment by bhaskarSingh** [comment]
![screen shot 2018-03-23 at 1 05 55 am](https://user-images.githubusercontent.com/16613455/37794095-7a8a8a5e-2e36-11e8-8661-9dda17168943.png)

What do you think about it, it has cleaner look it, don't you think?
I am also thinking about adding some text like about us etc

**Comment by rahuldcoder** [comment]
So which footer should we included??

**Comment by Logan1x** [comment]
we can ask in slack and can vote but I don't understand if its these are not clickable what meaning of it? for future?

**Comment by bhaskarSingh** [comment]
ya, for right now the foot icon doesn't do anything, but in future, the point is that user should be able to share the post by clicking these icons.
