### ISSUE TITLE
Search Feature?

### ISSUE THREAD

**Issue by ZechariahRaman** [Google-Front-End-Weekend-Projects/A-Tribute-To-Stephen-Hawking#4]
Is the search feature necessary? Search features are useful when dealing with a big website - one with many pages or lots of info. Is ours really quite that big?

**Comment by Logan1x** [comment]
I think we should add a search feature. maybe it's not big today but it will be (touchwood😅), another feature of search is we can use keywords to search so that they can be useful for once who is researching or preparing docs on something.

**Comment by rahuldcoder** [comment]
Yeah like, later on, we can add all his publications, ted talks etc. and then the site would eventually be very big.

**Comment by Soumya44** [comment]
the search feature is just for design purpose (prototype)
