### ISSUE TITLE
Add description and host a website on github pages

### ISSUE THREAD

**Issue by Logan1x** [Google-Front-End-Weekend-Projects/A-Tribute-To-Stephen-Hawking#5]
![image](https://user-images.githubusercontent.com/10944610/37815125-aff5b7f6-2e93-11e8-8907-9a83a6d9c95f.png)

**there is no description of project or website attached to repo description, so if someone look on org homepage he/she will not be seeing any description** 

![image](https://user-images.githubusercontent.com/10944610/37815247-13f4ecfe-2e94-11e8-9c91-f98215e6cb54.png)

**Comment by Soumya44** [comment]
Already hosted in GitHub pages

**Comment by Logan1x** [comment]
so can you put link in readme or description So that i'll we easily available to find

**Comment by Logan1x** [comment]
or give someone collaborator accsess.
